version: "3"

services:
  client:
    build: ../src/Crayons.Web
    networks:
      - crayons-net
    ports:
      - '5000:5000'

  api:
    build: ../src/Crayons.Api
    networks:
      - crayons-net
    ports:
      - '5001:5000'

  mssql:
    image: microsoft/mssql-server-linux
    networks:
      - crayons-net
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "Crayons123!."
      ACCEPT_EULA: "Y"

networks: 
  crayons-net:
    driver: bridge